version: 2.1
# prueba paralelo
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Compilar proyecto
          command: mvn clean compile

  test:
    docker:
      - image: cimg/openjdk:17.0
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Ejecutar pruebas
          command: mvn test

  quality:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Validar proyecto
          command: mvn validate

  package:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Empaquetar aplicación
          command: mvn package -DskipTests

workflows:
  version: 2

  validacion:
    jobs:
      - build
      - test
      - quality

  entrega:
    jobs:
      - package