apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingcart-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingcart
  template:
    metadata:
      labels:
        app: shoppingcart
    spec:
      containers:
        - name: shoppingcart
          image: nginx:latest
          ports:
            - containerPort: 80