apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingcart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingcart
  template:
    metadata:
      labels:
        app: shoppingcart
    spec:
      containers:
        - name: shoppingcart
          image: tomcat:9.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"